GET https://4d2cc376-a3d6-486e-9e54-22617a684b33.serverhub.praktikum-services.ru/api/v1/posts/

###
POST https://4d2cc376-a3d6-486e-9e54-22617a684b33.serverhub.praktikum-services.ru/

{
  "id": 5,
  "text": "9 \u043e\u043a\u0442. \u0412\u0438\u0434\u0435\u043b, \u043a\u0430\u043a \u043c\u0430\u0442\u044c \u0411\u0430\u0448\u043a\u0438\u0440\u0446\u0435\u0432\u043e\u0439 \u0438\u0433\u0440\u0430\u043b\u0430 \u0432 \u0440\u0443\u043b\u0435\u0442\u043a\u0443. \u041d\u0435\u043f\u0440\u0438\u044f\u0442\u043d\u043e\u0435 \u0437\u0440\u0435\u043b\u0438\u0449\u0435.",
  "author": 1,
  "pub_date": "2022-12-22T18:34:28.790071Z"
}




[Unit]
# это текстовое описание юнита, пояснение для разработчика
Description=gunicorn daemon 

# при старте операционной системы запускать процесс только после того, 
# как операционная система загрузится и настроит подключение к сети
After=network.target 

[Service]
# от чьего имени запускать процесс:
# укажите имя, под которым вы подключались к серверу
User=alex97 

# адрес к директории, где установлен Gunicorn
WorkingDirectory=/home/<имя-пользователя-в-системе>/
hw05_final/yatube/ 

# команду, которую вы запускали руками, теперь будет запускать systemd:
# в указанной директории будет выполнена команда bind
# и по запросу к 127.0.0.1:8000 будет выполнен файл запуска приложения yatube.wsgi
ExecStart=/home/alex97/
hw05_final/venv/bin/gunicorn --bind 127.0.0.1:8000 yatube.wsgi:application

[Install]
# группировка юнитов 
WantedBy=multi-user.target